// <auto-generated />
namespace Assignment5_SanghyukLee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class testMediaItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testMediaItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202008120249294_testMediaItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
